-- Kedai Rasa Kita POS Database Schema for Supabase

-- 1. PROFILES (Extends Supabase Auth users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin', 'cashier')),
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Function & Trigger to automatically handle profile creation on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, name, role, is_active)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'name', NEW.email),
    COALESCE(NEW.raw_user_meta_data->>'role', 'cashier'),
    true
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 2. CATEGORIES
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. PRODUCTS
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku TEXT UNIQUE,
  name TEXT NOT NULL,
  category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  price DECIMAL(12, 2) NOT NULL CHECK (price >= 0),
  stock_qty INT NOT NULL DEFAULT 0 CHECK (stock_qty >= 0),
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. SALES TRANSACTIONS
CREATE TABLE IF NOT EXISTS public.sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_number TEXT UNIQUE NOT NULL,
  cashier_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  total_amount DECIMAL(12, 2) NOT NULL,
  payment_method TEXT NOT NULL CHECK (payment_method IN ('cash', 'qris', 'debit', 'transfer')),
  status TEXT DEFAULT 'completed' CHECK (status IN ('completed', 'cancelled')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. SALE ITEMS
CREATE TABLE IF NOT EXISTS public.sale_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id BIGINT REFERENCES public.sales(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
  product_name TEXT NOT NULL,
  qty INT NOT NULL CHECK (qty > 0),
  price_at_sale DECIMAL(12, 2) NOT NULL
);

-- 6. STOCK LOGS
CREATE TABLE IF NOT EXISTS public.stock_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  change_qty INT NOT NULL,
  reason TEXT NOT NULL CHECK (reason IN ('sale', 'adjustment', 'refund')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ENABLE ROW LEVEL SECURITY
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sale_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_logs ENABLE ROW LEVEL SECURITY;

-- Helper function to check admin role
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin' AND is_active = true
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- PROFILES POLICIES
CREATE POLICY "Users can read own profile" ON public.profiles
  FOR SELECT USING (auth.uid() = id OR public.is_admin());
CREATE POLICY "Admins can insert/update profiles" ON public.profiles
  FOR ALL USING (public.is_admin());

-- CATEGORIES POLICIES
CREATE POLICY "Authenticated users can read categories" ON public.categories
  FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can manage categories" ON public.categories
  FOR ALL USING (public.is_admin());

-- PRODUCTS POLICIES
CREATE POLICY "Authenticated users can read products" ON public.products
  FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can manage products" ON public.products
  FOR ALL USING (public.is_admin());

-- SALES & SALE ITEMS POLICIES
CREATE POLICY "Authenticated users can create and read sales" ON public.sales
  FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can create and read sale items" ON public.sale_items
  FOR ALL USING (auth.role() = 'authenticated');

-- STOCK LOGS POLICIES
CREATE POLICY "Authenticated users can read stock logs" ON public.stock_logs
  FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can manage stock logs" ON public.stock_logs
  FOR ALL USING (public.is_admin());

-- Atomic checkout function (RPC)
CREATE OR REPLACE FUNCTION process_checkout(
  p_receipt_number TEXT,
  p_cashier_id UUID,
  p_total_amount DECIMAL,
  p_payment_method TEXT,
  p_items JSONB
) RETURNS BIGINT AS $$
DECLARE
  v_sale_id BIGINT;
  item RECORD;
BEGIN
  -- 1. Insert Sales Record
  INSERT INTO public.sales (receipt_number, cashier_id, total_amount, payment_method)
  VALUES (p_receipt_number, p_cashier_id, p_total_amount, p_payment_method)
  RETURNING id INTO v_sale_id;

  -- 2. Process Items & Update Stock
  FOR item IN SELECT * FROM jsonb_to_recordset(p_items) AS x(product_id BIGINT, product_name TEXT, qty INT, price DECIMAL)
  LOOP
    -- Insert Sale Item
    INSERT INTO public.sale_items (sale_id, product_id, product_name, qty, price_at_sale)
    VALUES (v_sale_id, item.product_id, item.product_name, item.qty, item.price);

    -- Decrement Product Stock
    UPDATE public.products
    SET stock_qty = stock_qty - item.qty
    WHERE id = item.product_id AND stock_qty >= item.qty;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Insufficient stock for product ID %', item.product_id;
    END IF;

    -- Insert Stock Log
    INSERT INTO public.stock_logs (product_id, change_qty, reason)
    VALUES (item.product_id, -item.qty, 'sale');
  END LOOP;

  RETURN v_sale_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

