-- Kedai Rasa Kita POS Database Schema for Supabase

-- 1. PROFILES (Extends Supabase Auth users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin', 'cashier')),
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. CATEGORIES
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. PRODUCTS
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku TEXT UNIQUE,
  name TEXT NOT NULL,
  category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  price DECIMAL(12, 2) NOT NULL CHECK (price >= 0),
  stock_qty INT NOT NULL DEFAULT 0 CHECK (stock_qty >= 0),
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. SALES TRANSACTIONS
CREATE TABLE IF NOT EXISTS public.sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_number TEXT UNIQUE NOT NULL,
  cashier_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  total_amount DECIMAL(12, 2) NOT NULL,
  payment_method TEXT NOT NULL CHECK (payment_method IN ('cash', 'qris', 'debit', 'transfer')),
  status TEXT DEFAULT 'completed' CHECK (status IN ('completed', 'cancelled')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. SALE ITEMS
CREATE TABLE IF NOT EXISTS public.sale_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sale_id BIGINT REFERENCES public.sales(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
  product_name TEXT NOT NULL,
  qty INT NOT NULL CHECK (qty > 0),
  price_at_sale DECIMAL(12, 2) NOT NULL
);

-- 6. STOCK LOGS
CREATE TABLE IF NOT EXISTS public.stock_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  change_qty INT NOT NULL,
  reason TEXT NOT NULL CHECK (reason IN ('sale', 'adjustment', 'refund')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS POLICIES
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sale_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_logs ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to read products & categories
CREATE POLICY "Allow authenticated read products" ON public.products FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated read categories" ON public.categories FOR SELECT USING (auth.role() = 'authenticated');

-- Atomic checkout function (RPC)
CREATE OR REPLACE FUNCTION process_checkout(
  p_receipt_number TEXT,
  p_cashier_id UUID,
  p_total_amount DECIMAL,
  p_payment_method TEXT,
  p_items JSONB
) RETURNS BIGINT AS $$
DECLARE
  v_sale_id BIGINT;
  item RECORD;
BEGIN
  -- 1. Insert Sales Record
  INSERT INTO public.sales (receipt_number, cashier_id, total_amount, payment_method)
  VALUES (p_receipt_number, p_cashier_id, p_total_amount, p_payment_method)
  RETURNING id INTO v_sale_id;

  -- 2. Process Items & Update Stock
  FOR item IN SELECT * FROM jsonb_to_recordset(p_items) AS x(product_id BIGINT, product_name TEXT, qty INT, price DECIMAL)
  LOOP
    -- Insert Sale Item
    INSERT INTO public.sale_items (sale_id, product_id, product_name, qty, price_at_sale)
    VALUES (v_sale_id, item.product_id, item.product_name, item.qty, item.price);

    -- Decrement Product Stock
    UPDATE public.products
    SET stock_qty = stock_qty - item.qty
    WHERE id = item.product_id AND stock_qty >= item.qty;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Insufficient stock for product ID %', item.product_id;
    END IF;

    -- Insert Stock Log
    INSERT INTO public.stock_logs (product_id, change_qty, reason)
    VALUES (item.product_id, -item.qty, 'sale');
  END LOOP;

  RETURN v_sale_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
